apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-prod
  labels:
    app: todo-frontend
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
      env: prod
  template:
    metadata:
      labels:
        app: todo-frontend
        env: prod
    spec:
      containers:
        - name: todo-frontend
          image: monupanwar1/todo-frontend:latest
          ports:
            - containerPort: 80
