name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo with GitHub token to allow push
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 2️⃣ Set up Docker Buildx (optional but good for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/react-todo-gitops
          TAG=${GITHUB_SHA::7} # short SHA for tag
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 5️⃣ Update deployment.yaml and push changes
      - name: Update deployment manifest
        run: |
          echo "Updating deployment.yaml with new image $IMAGE:$TAG"
          sed -i "s|image: .*|image: $IMAGE:$TAG|" k8s/dev/deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/dev/deployment.yaml
          git commit -m "Update dev deployment to $IMAGE:$TAG" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/monupanwar1/react-todo-gitops.git HEAD:main
        env:
          IMAGE: ${{ env.IMAGE }}
          TAG: ${{ env.TAG }}
